[package]
name = "helix_docopt"
version = "0.1.0"
authors = ["Terence Lee <hone02@gmail.com>", "Godfrey Chan <godfreykfc@gmail.com>"]

[lib]

crate-type = ["cdylib"]

[dependencies]
docopt = "0.8.1"
helix = "0.7.3"
